apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      #      tolerations:
      #        - operator: "Exists"
      #          effect: "NoExecute"
      #        - operator: "Exists"
      #          effect: "NoSchedule"
      containers:
        - image: squat/generic-device-plugin:6475ff5d0927c0f25b3a39a661aa657ca190d0ef
          name: generic-device-plugin
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
            - name: config
              mountPath: /etc/generic-device-plugin/config.yaml
              subPath: config.yaml
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
        - name: config
          configMap:
            name: generic-device-plugin-config
            defaultMode: 0640
  updateStrategy:
    type: RollingUpdate
