---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: kubernetes-api-external
spec:
  blocks:
    - cidr: "10.3.0.0/16"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.name": kubernetes-api-external
      "io.kubernetes.service.namespace": kubernetes-api-external
