---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  labels:
    monitoring.homelab.wojoinc.xyz/enabled: "true"
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: 'rook-ceph:cluster'
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 10s
      honorLabels: true
