---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-storage
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: cloud-storage
          targetRevision: "main"
  template:
    metadata:
      name: 'cloud-storage-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'cloud'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: '{{.values.targetRevision}}'
          path: argocd/clusters/{{ .name }}/cloud-storage/base
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
