---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana
spec:
  kubernetes:
    audiences: []
    role: "TO_BE_FILLED"
    serviceAccount: grafana-sa
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: homelab
  vaultConnectionRef: vault-secrets-operator/default
