---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-oauth
spec:
  destination:
    create: true
    name: grafana-oauth
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: monitoring/grafana/oauth
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: grafana
