---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: coder-env
spec:
  destination:
    create: true
    name: coder-env
  hmacSecretData: true
  mount: ""
  path: coder/coder/env
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: coder
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres
spec:
  destination:
    create: true
    name: coder-db-app
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: coder/postgres/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: postgres
