---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../common/ingress-forward-auth
  - ../../../common/ingress-publish-external
  - ../../../env/prod/ingress-tls
patches:
  # Doing this here sucks, but replacements makes it impossible to template this in a component
  # because variable substitution doesn't exist
  - target:
      kind: Ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: not-used
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: media-readarr-forward-auth-all@kubernetescrd,media-readarr-forward-auth@kubernetescrd
