---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  labels:
    app.kubernetes.io/name: unpackerr
  name: unpackerr-env
spec:
  destination:
    create: true
    name: unpackerr-env
    overwrite: false
    transformation: {}
  hmacSecretData: true
  mount: kv-homelab
  path: media/default/unpackerr-env
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: unpackerr
