---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/somerandow/homelab//argocd/app/immich/base?ref=main
components:
  - https://github.com/somerandow/homelab//argocd/app/immich/components/feature/hw-transcode?ref=main
  - https://github.com/somerandow/homelab//argocd/app/immich/components/feature/hw-ml?ref=main
  - https://github.com/somerandow/homelab//argocd/app/immich/components/feature/persistence?ref=main
  - https://github.com/somerandow/homelab//argocd/app/immich/components/feature/file-config?ref=main
