---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: home-assistant
                resources:
                  requests:
                    devices.wojoinc.xyz/thread: "1"
                    devices.wojoinc.xyz/zigbee: "1"
                  limits:
                    devices.wojoinc.xyz/thread: "1"
                    devices.wojoinc.xyz/zigbee: "1"
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: home.wojoinc.xyz
      - op: add
        path: /spec/tls/0/hosts/0
        value: home.wojoinc.xyz
