---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-auth-app
spec:
  destination:
    create: true
    name: redis-auth-app
  hmacSecretData: true
  mount: ""
  path: bookstack/bookstack/redis
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: bookstack
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-auth
spec:
  destination:
    create: true
    name: redis-auth
  hmacSecretData: true
  mount: ""
  path: bookstack/redis/auth
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: redis
