---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../../../common/ingress-publish-internal
#  - ../../feature/object-storage
configMapGenerator:
  - name: bookstack-env
    options:
      disableNameSuffixHash: true
    envs:
      - config.env
    behavior: merge
