---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../../../common/ingress-publish-internal
  - ../../feature/oidc
  - ../../feature/object-storage
configMapGenerator:
  - name: bookstack-env
    options:
      disableNameSuffixHash: true
    envs:
      - config.env
    behavior: merge
patches:
  # Required as cluster component is included after the cluster common component
  - target:
      kind: VaultStaticSecret
    path: patch-vaultstaticsecret.yaml
