---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - matrix:
        generators:
          - merge:
              mergeKeys:
                - app
              generators:
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/rook/git-generator-defaults.yaml"
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/clusters/**/rook/git-generator-overrides.yaml"
          - clusters:
              selector:
                matchLabels:
                  app.kubernetes.io/part-of: '{{.environment}}'
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'rook-{{.name}}' ## in case detailed name is required.
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{.environment}}'
        homelab.wojoinc.xyz/app-group: 'infra'
    spec:
      project: default ## Can use dynamic project name from git file generator. (project shoud be created before hand and can be part of bootstrap)
      sources:
        - repoURL: https://charts.rook.io/release
          targetRevision: '{{.chartVersion}}'
          chart: rook-ceph
          helm:
            # Helm values files for overriding values in the helm chart
            valueFiles:
              - $values/argocd/rook/values.yaml
              - $values/{{.path.path}}/values.yaml ## single isolated values file.
            skipCrds: false
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true          ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#create-namespace
          - ApplyOutOfSyncOnly=true       ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#selective-sync
          - ServerSideApply=true          ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply
          - RespectIgnoreDifferences=true ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
      ignoreDifferences: []               ## https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/
