---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          chartVersion: ">=0.10.0"
          namespace: vault-secrets-operator
  template:
    metadata:
      name: 'vault-secrets-operator-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'security'
    spec:
      project: default
      sources:
        - repoURL: https://helm.releases.hashicorp.com
          targetRevision: '{{.values.chartVersion}}'
          chart: vault-secrets-operator
          helm:
            releaseName: vso
            valueFiles:
              - $values/argocd/app/vault-secrets-operator/values.yaml
              - $values/argocd/clusters/{{.name}}/vault-secrets-operator/values.yaml
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/vault-secrets-operator/base
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
