---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: grafana-operator
          chartVersion: "v5.18.0"
  template:
    metadata:
      name: 'grafana-operator-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'operators'
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/grafana/helm-charts
          targetRevision: '{{.values.chartVersion}}'
          chart: grafana-operator
          helm:
            valueFiles:
              - $values/argocd/app/grafana-operator/values.yaml
              - $values/argocd/clusters/{{.name}}/grafana-operator/values.yaml
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
