---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          chartVersion: ">= 35.3.0"
          namespace: traefik
  template:
    metadata:
      name: 'traefik-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'infra'
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/traefik/helm
          targetRevision: '{{.values.chartVersion}}'
          chart: traefik
          helm:
            valueFiles:
              - $values/argocd/traefik/values.yaml
              - $values/argocd/clusters/{{.name}}/traefik/values.yaml
            skipCrds: false
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
