---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceph-rgw
spec:
  isCA: false
  secretName: ceph-rgw-cert
  commonName: ""
  dnsNames: []
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
