---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rgw-fast-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: rgw-fast
  objectStoreNamespace: rook-ceph
