---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: metrics-server
          targetRevision: 2b4f3e9bcc626737e9ef224a15bd8c4810261a8e
  template:
    metadata:
      name: 'metrics-server-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/kubernetes-sigs/metrics-server
          targetRevision: '{{.values.targetRevision}}'
          path: "charts/metrics-server"
          helm:
            valueFiles:
              - $values/argocd/app/metrics-server/values.yaml
              - $values/argocd/clusters/{{.name}}/metrics-server/values.yaml
            skipCrds: false
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
