monitoring:
  enabled: true
csi:
  serviceMonitor:
    enabled: true
    labels:
      monitoring.homelab.wojoinc.xyz/enabled: "true"
logLevel: INFO
obcAllowAdditionalConfigFields: "maxObjects,maxSize,bucketOwner"
