---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../env/prod/common
patches:
  - target:
      kind: PersistentVolumeClaim
      labelSelector: persistence.homelab.wojoinc.xyz/accessMode=RWX
    path: patch-rwx-pvc.yaml
  - target:
      kind: GrafanaDashboard
    path: patch-grafanadashboard.yaml
