---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../app/calibre/components/persistence
  - ../common
patches:
  - target:
      kind: Deployment
    path: patch-deployment.yaml
