---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../app/calibre/components/persistence
patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: rook-cephfs
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/1/emptyDir
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            volumes:
              - name: media
                persistentVolumeClaim:
                  claimName: tank-media
