---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          # renovate: datasource=github-releases depName=vmware-tanzu/helm-charts
          targetRevision: "12.0.0"
          namespace: velero
  template:
    metadata:
      name: 'velero-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'infra'
    spec:
      project: default
      sources:
        - repoURL: https://vmware-tanzu.github.io/helm-charts
          targetRevision: '{{.values.targetRevision}}'
          chart: velero
          helm:
            releaseName: velero
            valueFiles:
              - $values/argocd/app/velero/values/base/values.yaml
              - $values/argocd/app/velero/values/flavor/{{index .metadata.labels "cluster-flavor"}}/values.yaml
              - $values/argocd/app/velero/values/env/{{index .metadata.labels "cluster-environment"}}/values.yaml
              - $values/argocd/app/velero/values/cluster/{{.name}}/values.yaml
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/velero/base
          kustomize:
            components:
              - ../../../flavor/{{index .metadata.labels "cluster-flavor"}}/common
              - ../components/flavor/{{index .metadata.labels "cluster-flavor"}}/velero
              - ../../../env/{{index .metadata.labels "cluster-environment"}}/common
              - ../components/env/{{index .metadata.labels "cluster-environment"}}/velero
              - ../../../cluster/{{.name}}
              - ../components/cluster/{{.name}}/velero
            ignoreMissingComponents: true
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
