---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: replace
        path: /spec/commonName
        value: "homelab.wojoinc.xyz"
    target:
      kind: Certificate
      name: root-ca
