## Cert Manager values
global:
  logLevel: 3
prometheus:
  enabled: false
podLabels:
  app.kubernetes.io/part-of: prod
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
webhook:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
cainjector:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
startupapicheck:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
