---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../app/readarr/components/persistence
  - ../../../common/ingress-forward-auth
  - ../../../common/ingress-publish-external
  - ../../../env/prod/ingress-tls
patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: rook-rbd-fast
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/1/emptyDir
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            volumes:
              - name: media
                persistentVolumeClaim:
                  claimName: tank-media
  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: /spec/ingressClassName
        value: traefik-external
      - op: replace
        path: /spec/rules/0/host
        value: readarr.wojoinc.xyz
      - op: add
        path: /spec/tls/0/hosts/0
        value: readarr.wojoinc.xyz
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: "/books"
  # Doing this here sucks, but replacements makes it impossible to template this in a component
  # because variable substitution doesn't exist
  - target:
      kind: Ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: not-used
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: media-readarr-forward-auth@kubernetescrd,media-readarr-forward-auth-all@kubernetescrd
