---
ingress:
  main:
    className: "traefik-external"
    host: "readarr.wojoinc.xyz"
    path: "/books"
    forwardAuth:
      enabled: true
      endpoint: oauth2-proxy.oauth2-proxy.svc.homelab.wojoinc.local
persistence:
  config:
    enabled: true
    accessModes:
      - ReadWriteOnce
    className: "rook-rbd-fast"
  media:
    existingClaim: "tank-media"
    enabled: true
