---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: adguard-auth
  namespace: external-dns
spec:
  destination:
    create: true
    name: adguard-auth
  hmacSecretData: true
  mount: kv-homelab
  path: external-dns/external-dns-adguard/auth
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: external-dns-adguard
