---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              values:
                idp.host: kc.wojoinc.xyz
                namespace: monitoring
                role_attribute_path: "contains(groups[*], 'Monitoring Admins') && 'Admin' || 'Viewer'"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  cluster-environment: prod
              values:
                idp.realm: homelab
                host: grafana2.wojoinc.xyz
  template:
    metadata:
      name: 'grafana-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/grafana
          kustomize:
            patches:
              - target:
                  kind: Grafana
                  name: grafana
                patch: |-
                  apiVersion: grafana.integreatly.org/v1beta1
                  kind: Grafana
                  metadata:
                    name: not-used
                  spec:
                    config:
                      auth:
                        signout_redirect_url: https://{{ .values.idp.host }}/realms/{{ .values.idp.realm }}/protocol/openid-connect/logout
                      auth.generic_oauth:
                        auth_url: https://{{ .values.idp.host }}/realms/{{ .values.idp.realm }}/protocol/openid-connect/auth
                        token_url: https://{{ .values.idp.host }}/realms/{{ .values.idp.realm }}/protocol/openid-connect/token
                        api_url: https://{{ .values.idp.host }}/realms/{{ .values.idp.realm }}/protocol/openid-connect/userinfo
                        role_attribute_path: {{ .values.role_attribute_path }}
                      server:
                        root_url: https://{{ .values.host }}
              - target:
                  kind: Grafana
                  name: grafana
                patch: |-
                  - op: replace
                    path: /spec/ingress/spec/rules/0/host
                    value: {{ .values.host }}
                  - op: add
                    path: /spec/ingress/spec/tls/0/hosts/0
                    value: {{ .values.host }}
            components:
              - datasources/local-cluster
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
