---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - vaultauths.yaml
  - vaultstaticsecrets.yaml
patches:
  - target:
      kind: PodMonitor
    patch: |-
      - op: add
        path: /metadata/labels/monitoring.homelab.wojoinc.xyz~1enabled
        value: "true"
  - target:
      kind: Cluster
    patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: not-used
      spec:
        bootstrap:
          initdb:
            secret:
              name: nextcloud-db-app
        storage:
          storageClass: rook-rbd-fast
  - target:
      kind: RedisCluster
    patch: |-
      - op: add
        path: /spec/storage/volumeClaimTemplate/spec/storageClassName
        value: rook-rbd-fast
      - op: add
        path: /spec/storage/nodeConfVolumeClaimTemplate/spec/storageClassName
        value: rook-rbd-fast
