---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  annotations:
    persistence.homelab.wojoinc.xyz/accessMode: RWO
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
