---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flaresolverr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          # renovate: datasource=docker depName=ghcr.io/somerandow/charts/flaresolverr
          chartVersion: "2.0.0"
          namespace: media
  template:
    metadata:
      name: 'flaresolverr-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'media'
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/somerandow/charts
          targetRevision: '{{.values.chartVersion}}'
          chart: flaresolverr
          helm:
            releaseName: flaresolverr
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
