---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: CephCluster
    patch: |-
      apiVersion: ceph.rook.io/v1
      kind: CephCluster
      metadata:
        name: not-used
      spec:      
        network:
          addressRanges:
            public: [] # To be filled by cluster component
          provider: host
        storage:
          useAllDevices: true
          config:
            encryptedDevice: "true"
