---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: upstream-tls
  namespace: vault
spec:
  rootCAs:
    - homelab-ca-bundle
  serverName: '*.vault-internal.vault.svc.homelab.wojoinc.local'
