---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: replace
        path: /spec/acme/server
        value: "https://acme-v02.api.letsencrypt.org/directory"
    target:
      kind: ClusterIssuer
      name: acme
