---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  isCA: true
  commonName: "to be filled in"
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
