---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-cache
spec:
  storageClassName: rook-rbd-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
