---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      env: prod
patches:
  - target:
      kind: GrafanaDashboard
    path: patch-grafanadashboard.yaml
  - target:
      kind: Ingress
    path: patch-ingress.yaml
