---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prowlarr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          # renovate: datasource=docker depName=ghcr.io/somerandow/charts/arr
          targetRevision: "0.7.7"
          namespace: media
  template:
    metadata:
      name: 'prowlarr-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'media'
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/somerandow/charts
          targetRevision: '{{.values.targetRevision}}'
          chart: arr
          helm:
            releaseName: prowlarr
            valueFiles:
              - $values/argocd/app/prowlarr/values.yaml
              - $values/argocd/env/{{index .metadata.labels "cluster-environment"}}/prowlarr/values.yaml
              - $values/argocd/clusters/{{.name}}/prowlarr/values.yaml
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
