---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bookstack-oidc
spec:
  destination:
    create: true
    name: bookstack-oidc
  hmacSecretData: true
  mount: ""
  path: bookstack/bookstack/oidc
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: bookstack
