---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: PodMonitor
    patch: |-
      - op: add
        path: /metadata/labels/monitoring.homelab.wojoinc.xyz~1enabled
        value: "true"
resources:
  - configmap.yaml
