---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-environment: prod
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: prometheus-operator
          chartVersion: ">= 75.0.0"
  template:
    metadata:
      name: 'kube-prometheus-stack-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{ index .metadata.labels "cluster-environment" }}'
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: '{{.values.chartVersion}}'
          chart: kube-prometheus-stack
          helm:
            releaseName: "kube-prometheus-stack"
            skipCrds: true
            valueFiles:
              - $values/argocd/app/kube-prometheus-stack/values.yaml
              - '$values/argocd/clusters/{{.name}}/kube-prometheus-stack/values.yaml'
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
