---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - merge:
              mergeKeys:
                - app
              generators:
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: 'argocd/provider/{{ index .metadata.labels "cluster-provider"}}/kube-prometheus-stack/generator.yaml'
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: 'argocd/env/{{ index .metadata.labels "cluster-environment"}}/kube-prometheus-stack/generator.yaml'
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/app/kube-prometheus-stack/generator.yaml"
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/clusters/{{.name}}/kube-prometheus-stack/generator.yaml"
  template:
    metadata:
      name: 'kube-prometheus-stack-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{ index .metadata.labels "cluster-environment" }}'
        testlabel2: '{{ .providerValueApp }}'
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: '{{.chartVersion}}'
          chart: kube-prometheus-stack
          helm:
            releaseName: "kube-prometheus-stack"
            skipCrds: true
            valueFiles:
              - $values/argocd/app/kube-prometheus-stack/values.yaml
              - $values/argocd/{{.path.path}}/values.yaml
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/kube-prometheus-stack
          kustomize:
            patches:
              - target:
                  kind: Namespace
                patch: |-
                  - op: replace
                    path: /metadata/name
                    value: {{.namespace}}
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
