cleanPrometheusOperatorObjectNames: true
fullnameOverride: ""
global:
  rbac:
    create: true
    createAggregateClusterRoles: true
nodeExporter:
  enabled: false
alertmanager:
  enabled: false
  namespaceOverride: monitoring
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: "wojoinc.xyz."
      dns.homelab.wojoinc.xyz/publish-external: "true"
      cert-manager.io/cluster-issuer: acme
#      traefik.ingress.kubernetes.io/router.middlewares: media-forward-auth-all@kubernetescrd,media-forward-auth@kubernetescrd
    ingressClassName: traefik-external
    hosts:
      - alert.wojoinc.xyz
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: alert-cert
        hosts:
          - alert.wojoinc.xyz
  alertManagerSpec:
    useExistingSecret: true
    replicas: 2
    externalUrl: "https://alert2.wojoinc.xyz"
#    storageSpec:
#      volumeClaimTemplate:
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          storageClassName: openebs-zfspv-quicktank
#          resources:
#            requests:
#              storage: 1Gi
grafana:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
prometheus:
  enabled: false
prometheusOperator:
  enabled: true
  revisionHistoryLimit: 2
  clusterDomain: "homelab.wojoinc.xyz"
  resources: { }
  prometheusConfigReloader:
    resources: { }

kubeApiServer:
  serviceMonitor:
    additionalLabels:
      monitoring.homelab.wojoinc.xyz/enabled: "true"
kubelet:
  serviceMonitor:
    additionalLabels:
      monitoring.homelab.wojoinc.xyz/enabled: "true"
kubeControllerManager:
  serviceMonitor:
    additionalLabels:
      monitoring.homelab.wojoinc.xyz/control-plane: "true"
coreDns:
  serviceMonitor:
    additionalLabels:
      monitoring.homelab.wojoinc.xyz/enabled: "true"
kubeEtcd:
  serviceMonitor:
    additionalLabels:
      monitoring.homelab.wojoinc.xyz/enabled: "true"
kubeScheduler:
  serviceMonitor:
    additionalLabels:
      monitoring.homelab.wojoinc.xyz/enabled: "true"
