---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-ca-bundle
spec:
  sources:
    - secret:
        name: "ca-secret"
        key: "tls.crt"
  target:
    secret:
      key: "ca.crt"
