---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Grafana
    patch: |-
      apiVersion: grafana.integreatly.org/v1beta1
      kind: Grafana
      metadata:
        name: not-used
      spec:
        persistentVolumeClaim:
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            storageClassName: ""
        deployment:
          spec:
            template:
              spec:
                securityContext:
                  fsGroupChangePolicy: "OnRootMismatch"
                  fsGroup: 10001
                volumes:
                  - name: grafana-data
                    persistentVolumeClaim:
                      claimName: grafana-pvc
