---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - https://github.com/somerandow/manifests//immich/components/hw-transcode?ref=main
  - https://github.com/somerandow/manifests//immich/components/hw-ml?ref=main
  - https://github.com/somerandow/manifests//immich/components/persistence?ref=main
  - https://github.com/somerandow/manifests//immich/components/file-config?ref=main
