---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          chartVersion: ">= 7.17.0"
          namespace: oauth2-proxy
  template:
    metadata:
      name: 'oauth2-proxy-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'sec'
    spec:
      project: default
      sources:
        - repoURL: https://oauth2-proxy.github.io/manifests
          targetRevision: '{{.values.chartVersion}}'
          chart: oauth2-proxy
          helm:
            releaseName: oauth2-proxy
            valueFiles:
              - $values/argocd/app/oauth2-proxy/values.yaml
              - $values/argocd/clusters/{{.name}}/oauth2-proxy/values.yaml
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/oauth2-proxy/base
          kustomize:
            components:
              - ../../../clusters/{{.name}}/oauth2-proxy
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
