---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: velero
spec:
  kubernetes:
    audiences: []
    role: ""
    serviceAccount: velero
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: "homelab"
  vaultConnectionRef: vault-secrets-operator/default
