---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  labels:
    app: outline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      name: outline
      labels:
        app: outline
    spec:
      containers:
        - name: outline
          image: docker.getoutline.com/outlinewiki/outline:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: outline-redis-config
                optional: false
            - secretRef:
                name: outline-db-config
                optional: false
            - secretRef:
                name: outline-config
                optional: false
          env:
            - name: URL
              value: http://localhost:3000
#            - name: COLLABORATION_URL
#              value: http://localhost
            - name: FORCE_HTTPS
              value: "false"
      restartPolicy: Always
