---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline-db-app-user
spec:
  destination:
    create: true
    name: outline-db-app-user
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: outline/outline-db/app
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: outline-db
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis
spec:
  destination:
    create: true
    name: redis-auth
  hmacSecretData: true
  mount: ""
  path: outline/redis/auth
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: redis
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline-redis
spec:
  destination:
    create: true
    name: outline-redis-config
  hmacSecretData: true
  mount: ""
  path: outline/outline/redis
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: outline
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline-db
spec:
  destination:
    create: true
    name: outline-db-config
  hmacSecretData: true
  mount: ""
  path: outline/outline/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: outline
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline-config
spec:
  destination:
    create: true
    name: outline-config
  hmacSecretData: true
  mount: ""
  path: outline/outline/config
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: outline
