---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Ingress
      name: overseerr
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: overseerr.wojoinc.xyz
      - op: add
        path: /spec/ingress/spec/tls/0/hosts/0
        value: overseerr.wojoinc.xyz
  - target:
      kind: PersistentVolumeClaim
      name: overseerr-config
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-rbd-fast
