---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - vaultauth.yaml
  - vaultstaticsecrets.yaml
patches:
  - target:
      kind: PodMonitor
    patch: |-
      - op: add
        path: /metadata/labels/monitoring.homelab.wojoinc.xyz~1enabled
        value: "true"
  - target:
      kind: Cluster
    patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: not-used
      spec:
        bootstrap:
          initdb:
            secret:
              name: keycloak-db-app
            import:
              type: microservice
              databases:
                - keycloak
              source:
                externalCluster: old-keycloak
        storage:
          storageClass: rook-rbd-fast
        externalClusters:
          - name: old-keycloak
            connectionParameters:
              host: 10.3.0.0
              user: keycloak
              dbname: keycloak
            password:
              name: keycloak-db-app-old
              key: password
  - target:
      group: k8s.keycloak.org
      kind: Keycloak
    patch: |-
      - op: add
        path: /spec/hostname/hostname
        value: kc.wojoinc.xyz
# TODO: create KC resource, test DB import
