---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keycloak
spec:
  kubernetes:
    audiences:
      - vault.wojoinc.xyz
    role: homelab-default
    serviceAccount: keycloak-db
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: homelab
  vaultConnectionRef: vault-secrets-operator/default
