---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../clusters/homelab.wojoinc.xyz/kaneo
resources:
  - cluster.yaml
  - vaultauths.yaml
  - vaultstaticsecrets.yaml