---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kaneo-db-app-user
spec:
  destination:
    create: true
    name: kaneo-db-app-user
    overwrite: true
    type: kubernetes.io/basic-auth
  hmacSecretData: true
  mount: ""
  path: kaneo/kaneo-db/app
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: kaneo-db