---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/instance: immich
        app.kubernetes.io/component: server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: immich
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v2.1.0
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          envFrom:
            - configMapRef:
                name: immich-env
            - secretRef:
                name: immich-redis-config
            - secretRef:
                name: immich-db-config
          ports:
            - containerPort: 2283
              name: http
              protocol: TCP
            - name: metrics-api
              containerPort: 8081
              protocol: TCP
            - name: metrics-ms
              containerPort: 8082
              protocol: TCP
          livenessProbe: &probes
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probes
          startupProbe:
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/component: machine-learning
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/instance: immich
        app.kubernetes.io/component: machine-learning
    spec:
      serviceAccountName: immich
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2.1.0-release
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          envFrom:
            - configMapRef:
                name: immich-ml-env
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          livenessProbe: &probes
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe: *probes
          startupProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /cache
              name: model-cache
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: model-cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
