---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis
spec:
  destination:
    create: true
    name: redis-auth
  hmacSecretData: true
  mount: ""
  path: oauth2-proxy/redis/auth
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: redis
