---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis
spec:
  destination:
    create: true
    name: redis-auth
  hmacSecretData: true
  mount: ""
  path: immich/redis/auth
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: redis
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-redis
spec:
  destination:
    create: true
    name: immich-config
  hmacSecretData: true
  mount: ""
  path: immich/immich/config
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: immich
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-redis
spec:
  destination:
    create: true
    name: immich-redis-config
  hmacSecretData: true
  mount: ""
  path: immich/immich/redis
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: immich
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-db
spec:
  destination:
    create: true
    name: immich-db-config
  hmacSecretData: true
  mount: ""
  path: immich/immich/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: immich
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres
spec:
  destination:
    create: true
    name: immich-db-app
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: immich/postgres/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: postgres
