---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-runner-token
spec:
  destination:
    create: true
    name: gitlab-runner-token
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: gitlab-runner/gitlab-runner/token
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: gitlab-runner
