serviceAccount:
  create: true
service:
  port: 8686
image:
  repository: ghcr.io/home-operations/lidarr
  tag: 2.13.0
probes:
  livenessCmd:
    - /usr/bin/env
    - bash
    - -c
    - curl --fail localhost:8686/api/v1/system/status?apiKey=`IFS=\> && while read -d
      \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
