---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  ## https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    # https://argocd-applicationset.readthedocs.io/en/stable/Generators-Matrix/
    - matrix:
        generators:
          - merge:
              mergeKeys:
                - app
              generators:
                ## https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/cert-manager/git-generator-defaults.yaml"
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/clusters/**/cert-manager/git-generator-overrides.yaml"
          ## https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/
          - clusters:
              selector:
                ## required labels on the cluster secret, controls the logic of cluster selection on the basis of labels/filters.
                matchLabels:
                  app.kubernetes.io/part-of: '{{.environment}}' ## filter on environment type
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'cert-manager-resources-{{.environment}}' ## in case detailed name is required.
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{.environment}}'
        homelab.wojoinc.xyz/app-group: 'infra'
    spec:
      project: default ## Can use dynamic project name from git file generator. (project shoud be created before hand and can be part of bootstrap)
      sources:
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: 'argocd/cert-manager/resources'
          kustomize:
            patches:
              - target:
                  kind: Certificate
                  name: root-ca
                patch: |-
                  kind: Certificate
                  metadata:
                    name: not-used
                  spec:
                    commonName: {{.clusterCommonName}}
      destination:
        server: '{{.server}}'
        namespace: '{{.path.basenameNormalized}}'
      syncPolicy:
        ## https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automated-sync-policy
        automated:
          prune: true
          selfHeal: true
        ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#sync-options
        syncOptions:
          - CreateNamespace=true          ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#create-namespace
          - ApplyOutOfSyncOnly=true       ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#selective-sync
          - ServerSideApply=true          ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply
          - RespectIgnoreDifferences=true ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
      ignoreDifferences: []               ## https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/
