---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-chunks
spec:
  bucketName: loki-chunks
  storageClassName: rgw-fast-bucket
  additionalConfig:
    bucketOwner: loki
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-ruler
spec:
  bucketName: loki-ruler
  storageClassName: rgw-fast-bucket
  additionalConfig:
    bucketOwner: loki
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-admin
spec:
  bucketName: loki-admin
  storageClassName: rgw-fast-bucket
  additionalConfig:
    bucketOwner: loki
