---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../feature/persistence
  - ../../feature/database
  - ../../feature/oauth
  - ../../feature/datasource/local-cluster
patches:
  - target:
      kind: Grafana
      name: grafana
    path: patch-grafana.yaml
