ingressRoute:
  dashboard:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: acme
      kubernetes.io/ingress.class: traefik-external
      dns.homelab.wojoinc.xyz/publish-internal: 'true'
      external-dns.alpha.kubernetes.io/target: wojoinc.xyz.
    matchRule: Host(`traefik-external.wojoinc.xyz`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["websecure"]
service:
  spec:
    externalTrafficPolicy: Local
    internalTrafficPolicy: Cluster
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 7
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 60
          type: Utilization
      type: Resource
metrics:
  prometheus:
    service:
      enabled: true
      labels:
        monitoring.homelab.wojoinc.xyz/enabled: "true"
    disableAPICheck: false
    serviceMonitor:
      interval: 30s
      honorLabels: true
      scrapeTimeout: 5s
      honorTimestamps: true
      enableHttp2: true
      additionalLabels:
        monitoring.homelab.wojoinc.xyz/enabled: "true"
