---
serviceAccount:
  create: true
  name: renovate
cronjob:
  timeZone: America/Chicago
  initContainers:
    - name: app-installation-token
      image: ghcr.io/mshekow/github-app-installation-token:latest
      envFrom:
        - secretRef:
            name: renovate-github-app
      args:
        - "$(client_id)"
        - "$(install_id)"
        - "/var/run/secrets/private-key"
      volumeMounts:
        - name: private-key
          mountPath: /var/run/secrets/private-key
          subPath: private-key
renovate:
  config: |
    {
      "platform": "github",
      "autodiscover": true,
      "dryRun": null
    }
envFrom:
  - secretRef:
      name: renovate-github-app
  - secretRef:
      name: renovate-redis-auth
extraVolumes:
  - name: private-key
    secret:
      secretName: renovate-github-app
      items:
        - key: private_key
          path: private-key
