---
serviceAccount:
  create: true
  name: renovate
renovate:
  config: |
    {
      "platform": "github",
      "autodiscover": true,
      "autodiscoverFilter": ["/somerandow\/(charts|homelab)/"],
      "dryRun": null,
    }
envFrom:
  - secretRef:
      name: renovate-github-auth
  - secretRef:
      name: renovate-redis-auth
