---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: GrafanaDashboard
    patch: |-
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDashboard
      metadata:
        name: not-used
      spec:
        instanceSelector:
          matchLabels:
            monitoring.homelab.wojoinc.xyz/grafana-instance: grafana
