---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calibre-config
  labels:
    persistence.homelab.wojoinc.xyz/accessMode: RWX
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
