injector:
  enabled: false
global:
  tlsDisable: false
server:
  image:
    tag: "1.19.5"
  extraEnvironmentVars:
    VAULT_CAPATH: "/tls/ca.crt"
  updateStrategyType: "OnDelete"
  standalone:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 500m
  affinity: ""
ui:
  enabled: false
