---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ksca
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - matrix:
        generators:
          - merge:
              mergeKeys:
                - app
              generators:
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/ksca/git-generator-defaults.yaml"
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/clusters/**/ksca/git-generator-overrides.yaml"
          - clusters:
              selector:
                matchLabels:
                  app.kubernetes.io/part-of: '{{.environment}}'
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'ksca-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{.environment}}'
        homelab.wojoinc.xyz/app-group: 'infra'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/alex1989hu/kubelet-serving-cert-approver
          targetRevision: '{{.repoRef}}'
          path: "deploy/ha"
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true          ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#create-namespace
          - ApplyOutOfSyncOnly=true       ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#selective-sync
          - ServerSideApply=true          ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply
          - RespectIgnoreDifferences=true ## https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
      ignoreDifferences: []               ## https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/
