apiService:
  # TODO NEEDS a kustomization
  insecureSkipTLSVerify: false
tls:
  type: "cert-manager"
  clusterDomain: homelab.wojoinc.local
  certManager:
    addInjectorAnnotations: true
    existingIssuer:
      enabled: true
      kind: "ClusterIssuer"
      name: "homelab-ca"
    duration: "2592000s"
    renewBefore: "604800s"
