---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - pvc.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/0/emptyDir
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            volumes:
              - name: config
                persistentVolumeClaim:
                  claimName: readarr-config
