---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readarr-config
  labels:
    app.kubernetes.io/name: "readarr"
    app.kubernetes.io/instance: "readarr"
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
