---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../../../common/ingress-publish-internal
  - ../../../../../common/ingress-publish-external
patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: library.wojoinc.xyz
      - op: add
        path: /spec/tls/0/hosts/0
        value: library.wojoinc.xyz
  - target:
      kind: Deployment
    path: patch-deployment.yaml
