---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - ingress.yaml
  - prometheus.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
