---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: prometheus
automountServiceAccountToken: true
