---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - "monitor"
  endpoints:
  - port: http-web
    path: "/metrics"
  - port: reloader-web
    path: "/metrics"
