crds:
  enabled: true
  keep: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
resources:
  requests:
    cpu: 20m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 400Mi
webhook:
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 150Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
cainjector:
  resources:
    requests:
      cpu: 20m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 400Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
  - --enable-gateway-api
