---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: readarr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          targetRevision: "0.7.5"
          namespace: media
  template:
    metadata:
      name: 'readarr-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'media'
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/somerandow/charts
          targetRevision: '{{.values.targetRevision}}'
          chart: arr
          helm:
            releaseName: readarr
            valueFiles:
              - $values/argocd/app/readarr/values.yaml
              - $values/argocd/env/{{index .metadata.labels "cluster-environment"}}/readarr/values.yaml
              - $values/argocd/clusters/{{.name}}/readarr/values.yaml
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: $values
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
