apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
spec:
  metadataPool:
    deviceClass: ssd
    enableCrushUpdates: true
    replicated:
      size: 3
  dataPools:
    - name: replicated
      enableCrushUpdates: true
      deviceClass: ssd
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
