---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: homeassistant-prometheus
spec:
  destination:
    create: true
    name: homeassistant-prometheus
  hmacSecretData: true
  mount: ""
  path: home-assistant/homeassistant/prometheus
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: homeassistant
