---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-environment: prod
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: node-exporter
          chartVersion: ">= 4.47.0"
  template:
    metadata:
      name: 'node-exporter-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{ index .metadata.labels "cluster-environment" }}'
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision: '{{.values.chartVersion}}'
          chart: prometheus-node-exporter
          helm:
            releaseName: "node-exporter"
            skipCrds: true
            valueFiles:
              - $values/argocd/app/node-exporter/values.yaml
              - '$values/argocd/clusters/{{.name}}/values.yaml'
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/node-exporter/base
          kustomize:
            commonAnnotations:
              argocd.argoproj.io/sync-wave: "0"
            components:
              - ../../../flavor/{{index .metadata.labels "cluster-flavor"}}/node-exporter
            ignoreMissingComponents: false
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
