---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-csi-driver
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: cert-manager-csi-driver
          chartVersion: ">=v0.10.4"
  template:
    metadata:
      name: 'cert-manager-csi-driver-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'infra'
    spec:
      project: default
      sources:
        - repoURL: https://charts.jetstack.io
          targetRevision: '{{ .values.chartVersion }}'
          chart: cert-manager-csi-driver
          helm:
            releaseName: cert-manager-csi-driver
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/cert-manager-csi-driver/base
          kustomize:
            commonAnnotations:
              argocd.argoproj.io/sync-wave: "0"
            components:
              - ../../../flavor/{{index .metadata.labels "cluster-flavor"}}/cert-manager-csi-driver
            ignoreMissingComponents: false
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
