---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../feature/redis
configMapGenerator:
  - name: bookstack-env
    options:
      disableNameSuffixHash: true
    envs:
      - config.env
    behavior: merge
