---
ingress:
  main:
    enabled: true
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: acme
      dns.homelab.wojoinc.xyz/publish-external: "true"
      external-dns.alpha.kubernetes.io/target: wojoinc.xyz.
  api:
    enabled: true
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: acme
      dns.homelab.wojoinc.xyz/publish-external: "true"
      external-dns.alpha.kubernetes.io/target: wojoinc.xyz.
