---
global:
  extraArgs:
    # Allow the use of env var references in config
    - '--config.expand-env=true'
    - '--common.storage.s3.http.ca-file=/var/run/secrets/storage-tls/ca.crt'
  extraEnvFrom:
    - secretRef:
        name: loki-chunks
  extraVolumeMounts:
    - name: storage-tls
      mountPath: /var/run/secrets/storage-tls
  extraVolumes:
    - name: storage-tls
      secret:
        secretName: homelab-ca-bundle
loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    per_stream_rate_limit: 5MB
    per_stream_rate_limit_burst: 20MB
    max_line_size: 1MB
    max_line_size_truncate: true
  ruler:
    enable_api: true
  storage:
    bucketNames:
      admin: loki-admin
      chunks: loki-chunks
      ruler: loki-ruler
    type: s3
    s3:
      endpoint: "rook-ceph-rgw-rgw-fast.rook-ceph.svc"
      accessKeyId: "${AWS_ACCESS_KEY_ID}"
      secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
      s3ForcePathStyle: true
deploymentMode: Distributed
ingester:
  replicas: 3
querier:
  replicas: 3
  maxUnavailable: 2
queryFrontend:
  replicas: 2
  maxUnavailable: 1
queryScheduler:
  replicas: 2
distributor:
  replicas: 3
  maxUnavailable: 2
compactor:
  replicas: 1
indexGateway:
  replicas: 2
  maxUnavailable: 1
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
singleBinary:
  replicas: 0
minio:
  enabled: false
