---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: velero-aws-credentials
spec:
  destination:
    create: true
    name: aws-credentials
  hmacSecretData: true
  mount: "kv-homelab"
  path: velero/velero/aws/credentials
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: velero
