---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vaultwarden
spec:
  kubernetes:
    audiences:
      - vault.wojoinc.xyz
    role: homelab-default
    serviceAccount: default
    tokenExpirationSeconds: 600
  method: kubernetes
  mount: homelab
  vaultConnectionRef: vault-operator/default
