---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-env
spec:
  destination:
    create: true
    name: vaultwarden-env
  hmacSecretData: true
  mount: kv-homelab
  path: vaultwarden/default/env
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: vaultwarden
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-db-auth
spec:
  destination:
    create: true
    name: vaultwarden-db-auth
  hmacSecretData: true
  mount: kv-homelab
  path: vaultwarden/default/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: vaultwarden
