---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - vaultstaticsecret.yaml
patches:
  - target:
      kind: Deployment
      name: immich-server
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: server 
                volumeMounts:
                  - mountPath: /etc/immich.json
                    subPath: immich.json
                    name: config
            volumes:
              - name: config
                secret:
                  secretName: immich-config
                  items:
                    - key: immich.json
                      path: immich.json
  - target:
      kind: ConfigMap
      name: immich-env
    patch: |-
      - op: add
        path: /data/IMMICH_CONFIG_FILE
        value: /etc/immich.json
