---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-config
spec:
  destination:
    create: true
    name: immich-config
    # Drop all keys, then add field for immich.json by passing flat secret through a toJson
    transformation:
      excludes:
        - ".*"
      templates:
        immich.json:
          text: |
            {{- mustToPrettyJson .Secrets -}}
  hmacSecretData: true
  mount: ""
  path: immich/immich/config
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: immich
