ingress:
  main:
    className: "traefik-external"
    host: "lidarr.wojoinc.xyz"
    forwardAuth:
      enabled: true
      endpoint: oauth2-proxy.oauth2-proxy.svc.homelab.wojoinc.local
  api:
    className: "traefik-external"
    host: "lidarr.wojoinc.xyz"
    path: "/api"
    forwardAuth:
      enabled: false
persistence:
  config:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: "2Gi"
    className: "rook-rbd-fast"
  media:
    existingClaim: "tank-media"
    enabled: true
