---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: headlamp-oidc
spec:
  destination:
    create: true
    name: oidc-config
  hmacSecretData: true
  mount: kv-homelab
  path: headlamp/headlamp/oidc-config
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: headlamp
