---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
  labels:
    app.kubernetes.io/name: "plex"
    app.kubernetes.io/instance: "plex"
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
