---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../app/ombi/components/postgres
  - ../../../app/ombi/components/persistence
resources:
  - vaultauth.yaml
  - vaultstaticsecret.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: rook-rbd-fast
  - target:
      kind: Ingress
    patch: |-
      - op: add
        path: /spec/ingressClassName
        value: traefik-external
      - op: replace
        path: /spec/rules/0/host
        value: requests.wojoinc.xyz
      - op: add
        path: /spec/tls/0/hosts/0
        value: requests.wojoinc.xyz
  - target:
      kind: PodMonitor
    patch: |-
      - op: add
        path: /metadata/labels/monitoring.homelab.wojoinc.xyz~1enabled
        value: "true"
  - target:
      kind: Cluster
    patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: not-used
      spec:
        bootstrap:
          initdb:
            secret:
              name: ombi-db-app
        storage:
          storageClass: rook-rbd-fast
