---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ombi-db-init
spec:
  destination:
    create: true
    name: ombi-db-init
  hmacSecretData: true
  mount: kv-homelab
  path: media/ombi/db
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: ombi
