---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bookstack-app-key
spec:
  destination:
    create: true
    name: bookstack-app-key
  hmacSecretData: true
  mount: ""
  path: bookstack/bookstack/config
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: bookstack
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bookstack-db-root
spec:
  destination:
    create: true
    name: bookstack-db-root
  hmacSecretData: true
  mount: ""
  path: bookstack/mariadb/root
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: mariadb
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bookstack-db-user
spec:
  destination:
    create: true
    name: bookstack-db-user
  hmacSecretData: true
  mount: ""
  path: bookstack/mariadb/user
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: mariadb
