---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - matrix:
        generators:
          - merge:
              mergeKeys:
                - app
              generators:
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/grafana/git-generator-defaults.yaml"
                - git:
                    repoURL: https://github.com/somerandow/homelab
                    revision: main
                    files:
                      - path: "argocd/clusters/**/grafana/git-generator-overrides.yaml"
          - clusters:
              selector:
                ## required labels on the cluster secret, controls the logic of cluster selection on the basis of labels/filters.
                matchLabels:
                  app.kubernetes.io/part-of: '{{.environment}}' ## filter on environment type
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'grafana-{{.name | slugify}}' ## in case detailed name is required.
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{.environment}}'
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/grafana
          kustomize:
            patches:
              - target:
                  kind: Grafana
                  name: grafana
                patch: |-
                  apiVersion: grafana.integreatly.org/v1beta1
                  kind: Grafana
                  metadata:
                    name: not-used
                  spec:
                    config:
                      auth:
                        signout_redirect_url: {{.config.signout_redirect_url}}
                      auth.generic_oauth:
                        auth_url: {{.config.auth_url}}
                        token_url: {{.config.token_url}}
                        api_url: {{.config.api_url}}
                        role_attribute_path: {{.config.role_attribute_path}}
                      server:
                        root_url: {{.config.root_url}}
              - target:
                  kind: Grafana
                  name: grafana
                patch: |-
                  - op: replace
                    path: /spec/ingress/spec/rules/0/host
                    value: {{.ingress.host}}
                  - op: add
                    path: /spec/ingress/spec/tls/0/hosts/0
                    value: {{.ingress.host}}

      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
