---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../../app/grafana/components/persistence
  - ../../../app/grafana/components/database
  - ../../../app/grafana/components/oauth
  - ../../../app/grafana/datasources/local-cluster
patches:
  - target:
      kind: Grafana
      name: grafana
    path: patch-grafana.yaml
