---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: immich
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: immich
          targetRevision: "main"
  template:
    metadata:
      name: 'immich-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'media'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: '{{.values.targetRevision}}'
          path: argocd/app/immich/base
          kustomize:
            components:
              - ../../../env/{{ index .metadata.labels "cluster-environment" }}/ingress-tls
              - ../../../clusters/{{ .name }}/immich
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
