---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homeassistant
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-environment: prod
            argocd.argoproj.io/secret-type: cluster
        values:
          namespace: home-assistant
  template:
    metadata:
      name: 'homeassistant-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        app.kubernetes.io/part-of: '{{ index .metadata.labels "cluster-environment" }}'
        homelab.wojoinc.xyz/app-group: 'monitoring'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/homeassistant/base
          kustomize:
            components:
              - ../../../flavor/{{index .metadata.labels "cluster-flavor"}}
              - ../components/flavor/{{index .metadata.labels "cluster-flavor"}}
              - ../../../env/{{index .metadata.labels "cluster-environment"}}
              - ../components/env/{{index .metadata.labels "cluster-environment"}}
              - ../../../cluster/{{.name}}
              - ../components/cluster/{{.name}}
            ignoreMissingComponents: true
      destination:
        server: '{{.server}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
