---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates.yaml
  - middleware.yaml
  - redisreplication.yaml
  - redissentinel.yaml
  - serviceaccounts.yaml
  - serverstransport.yaml
