---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-headers
spec:
  headers:
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
