---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../clusters/homelab.wojoinc.xyz/nextcloud
resources:
  - cluster.yaml
  - configmap.yaml
  - podmonitor.yaml
  - rediscluster.yaml
  - serviceaccounts.yaml
