---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns-adguard
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - 'missingkey=error'
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          chartVersion: ">=1.17.0"
          namespace: external-dns
  template:
    metadata:
      name: 'external-dns-adguard-{{.name | slugify}}'
      labels:
        app.kubernetes.io/component: argocd-application
        homelab.wojoinc.xyz/app-group: 'media'
    spec:
      project: default
      sources:
        - repoURL: https://kubernetes-sigs.github.io/external-dns/
          targetRevision: '{{.values.chartVersion}}'
          chart: external-dns
          helm:
            releaseName: external-dns-adguard
            valueFiles:
              - $values/argocd/app/external-dns-adguard/values.yaml
              - $values/argocd/clusters/{{.name}}/external-dns-adguard/values.yaml
            skipCrds: false
            ignoreMissingValueFiles: true
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/somerandow/homelab'
          targetRevision: main
          path: argocd/app/external-dns-adguard/base
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences: []
