---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
data:
  config.yml: |
    log:
      level: DEBUG
    database:
      type: postgres
      user: vikunja
      host: vikunja-db-rw
    auth:
      openid:
        providers:
          keycloak:
            name: Keycloak
            scope: "openid email profile groups offline_access"
            requireAvailability: true
    defaultsettings:
      avatar_provider: gravatar
      discoverable_by_name: true
      discoverable_by_email: true
      timezone: America/Chicago
      language: en