---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vikunja-db-app-user
spec:
  destination:
    create: true
    name: vikunja-db-app-user
    overwrite: true
    type: kubernetes.io/basic-auth
  hmacSecretData: true
  mount: ""
  path: vikunja/vikunja-db/app
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: vikunja-db
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vikunja-app-oidc
spec:
  destination:
    create: true
    name: vikunja-app-oidc
    overwrite: true
  hmacSecretData: true
  mount: ""
  path: vikunja/vikunja/oidc
  refreshAfter: 5s
  type: kv-v2
  vaultAuthRef: vikunja